"""Self-play data generation for training (run on your PC).

Produces training examples: for every position in a game we store
   (encoded_board, policy_target, value_target)
where value_target is the eventual game result from HAN's perspective
(+1 HAN win, -1 CHO win, 0 draw) and policy_target is either a bootstrap
one-hot target or the MCTS root visit distribution.

Bootstrapping
-------------
Iteration 0 has no trained net yet, so games are generated by the EXISTING
alpha-beta engine (search.Engine). That already plays a reasonable game, which
gives the value net a sensible starting signal. Later iterations use the
trained policy+value net through PUCT MCTS to improve the data.

Output: a .npz-style list pickled to disk (we use json-lines of flat ints to
avoid a numpy dependency here; train.py converts to tensors).

Run:
    python -m janggi.selfplay --games 200 --out data/selfplay_iter0.jsonl
"""
from __future__ import annotations

import argparse
import json
import random
import time

from janggi.board import Board, Move, CHO, HAN, FORMATIONS
from janggi.search import Engine
from janggi.score import judge
from janggi.nn_encode import encode_flat
from janggi.repetition import RepetitionTracker
from janggi.mcts import NeuralMCTS


def _move_to_index(fr: int, fc: int, tr: int, tc: int) -> int:
    return (fr * 9 + fc) * 90 + (tr * 9 + tc)


def play_one_game(
    depth: int,
    max_moves: int = 200,
    temperature_moves: int = 12,
    mcts: NeuralMCTS | None = None,
):
    """Play one bootstrap or neural-MCTS game and return examples + winner."""
    forms = list(FORMATIONS.keys())
    cf, hf = random.choice(forms), random.choice(forms)
    board = Board.standard(cf, hf)
    tracker = RepetitionTracker()
    tracker.record(board)
    history: list[
        tuple[list[float], tuple[int, int, int, int], dict[tuple[int, int, int, int], float], int]
    ] = []
    forced_winner: str | None = None

    for ply in range(max_moves):
        side = board.side_to_move
        legal = board.legal_moves(side)
        forbidden = {
            move.as_tuple() for move in legal
            if tracker.would_repeat_thrice(board, move)
        }
        # No legal move, or only moves that illegally repeat for the third
        # time, loses for the side to move under the engine's game rules.
        if not legal or len(forbidden) == len(legal):
            forced_winner = "han" if -side == HAN else "cho"
            break
        if mcts is not None:
            # AlphaZero path: visits, not the sampled move, are the policy target.
            mv, policy = mcts.search(
                board,
                temperature=1.0 if ply < temperature_moves else 0.0,
                add_root_noise=True,
                forbidden_moves=forbidden,
            )
        else:
            eng = Engine(max_depth=depth, time_limit=20.0)
            # Bootstrap path: retain the classic alpha-beta player. Its selected
            # move becomes a one-hot policy target for iteration zero.
            if ply < temperature_moves:
                mv = _soft_choice(board, side, forbidden)
            else:
                mv, _ = eng.search(board, side, forbidden_moves=forbidden)
            policy = {mv.as_tuple(): 1.0} if mv is not None else {}
        if mv is None:
            forced_winner = "han" if -side == HAN else "cho"
            break
        history.append((encode_flat(board), mv.as_tuple(), policy, side))
        board.make(mv)
        tracker.record(board)
        # Mate/stalemate is a forced result, not a material-score decision.
        if not board.legal_moves(board.side_to_move):
            forced_winner = "han" if side == HAN else "cho"
            break

    winner = forced_winner or judge(board).get("winner", "draw")
    return history, winner


def _soft_choice(
    board: Board,
    side: int,
    forbidden_moves: set[tuple[int, int, int, int]] | None = None,
) -> Move | None:
    """Pick randomly among the top few root moves (diversifies openings)."""
    moves = board.legal_moves(side)
    if forbidden_moves:
        moves = [move for move in moves if move.as_tuple() not in forbidden_moves]
    if not moves:
        return None
    # Cheap shallow scores for variety; full search would be wasteful here.
    shallow = Engine(max_depth=2, time_limit=5.0)
    shallow._ext_budget = shallow.EXT_BUDGET
    shallow._killers = {}
    shallow._history = {}
    shallow._deadline = None
    scored = []
    for mv in moves:
        board.make(mv)
        s = -shallow._negamax(board, -side, 1, -10**9, 10**9)
        board.unmake()
        scored.append((s, mv))
    scored.sort(key=lambda x: x[0], reverse=True)
    top = scored[: min(4, len(scored))]
    return random.choice(top)[1]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--games", type=int, default=100)
    ap.add_argument("--depth", type=int, default=4)
    ap.add_argument("--out", default="data/selfplay.jsonl")
    ap.add_argument("--net", default=None, help="trained .pt for neural MCTS self-play")
    ap.add_argument("--simulations", type=int, default=200, help="MCTS simulations per move")
    ap.add_argument("--device", default=None, help="torch device, e.g. cuda or cpu")
    args = ap.parse_args()

    mcts = None
    if args.net:
        from janggi.nn_eval import load_net, nn_policy_value
        if not load_net(args.net, args.device):
            raise SystemExit("could not load neural net (is torch installed?)")
        mcts = NeuralMCTS(nn_policy_value, simulations=args.simulations)
        print(f"neural MCTS: {args.simulations} simulations/move")

    t0 = time.time()
    n_pos = 0
    with open(args.out, "w") as f:
        for gi in range(args.games):
            history, winner = play_one_game(args.depth, mcts=mcts)
            val = {"han": 1.0, "cho": -1.0}.get(winner, 0.0)
            for flat, mv, policy, side in history:
                sparse_policy = [
                    [_move_to_index(*move), probability]
                    for move, probability in policy.items()
                    if probability > 0.0
                ]
                rec = {
                    "b": [int(x) for x in flat],
                    "m": list(mv),
                    "p": sparse_policy,
                    "v": val,
                    "s": side,
                    "g": gi,
                }
                f.write(json.dumps(rec) + "\n")
                n_pos += 1
            if (gi + 1) % 10 == 0:
                dt = time.time() - t0
                print(f"  {gi+1}/{args.games} games, {n_pos} positions, {dt:.0f}s")
    print(f"done: {n_pos} positions -> {args.out} ({time.time()-t0:.0f}s)")


if __name__ == "__main__":
    main()
