"""Self-play data generation for training (run on your PC).

Produces training examples: for every position in a game we store
   (encoded_board, policy_target, value_target)
where value_target is the eventual game result from HAN's perspective
(+1 HAN win, -1 CHO win, 0 draw) and policy_target is the move actually chosen
(one-hot for bootstrap; visit-count distribution once MCTS is added).

Bootstrapping
-------------
Iteration 0 has no trained net yet, so games are generated by the EXISTING
alpha-beta engine (search.Engine). That already plays a reasonable game, which
gives the value net a sensible starting signal. Later iterations should plug in
the trained net (via an MCTS or net-guided player) to improve the data — that's
the AlphaZero loop. For now this script supports the alpha-beta bootstrap, which
is the right first step and needs no GPU.

Output: a .npz-style list pickled to disk (we use json-lines of flat ints to
avoid a numpy dependency here; train.py converts to tensors).

Run:
    python -m janggi.selfplay --games 200 --out data/selfplay_iter0.jsonl
"""
from __future__ import annotations

import argparse
import json
import random
import time

from janggi.board import Board, Move, CHO, HAN, FORMATIONS
from janggi.search import Engine
from janggi.score import judge
from janggi.nn_encode import encode_flat
from janggi.repetition import RepetitionTracker


def play_one_game(depth: int, max_moves: int = 200, temperature_moves: int = 12):
    """Play a single self-play game with the alpha-beta engine. Returns a list of
    (flat_board, move_tuple, side) per ply, plus the final result string."""
    forms = list(FORMATIONS.keys())
    cf, hf = random.choice(forms), random.choice(forms)
    board = Board.standard(cf, hf)
    tracker = RepetitionTracker()
    tracker.record(board)
    history: list[tuple[list[float], tuple[int, int, int, int], int]] = []

    for ply in range(max_moves):
        side = board.side_to_move
        eng = Engine(max_depth=depth, time_limit=20.0)
        # Early-game randomization: pick among near-best moves to diversify data,
        # so the net doesn't see the same opening every game.
        if ply < temperature_moves:
            mv = _soft_choice(eng, board, side)
        else:
            mv, _ = eng.search(board, side)
        if mv is None:
            break
        history.append((encode_flat(board), mv.as_tuple(), side))
        board.make(mv)
        tracker.record(board)
        # Stop on no legal reply (mate) or threefold-ish repetition.
        if not board.legal_moves(board.side_to_move):
            break

    result = judge(board)
    winner = result.get("winner", "draw")
    return history, winner


def _soft_choice(eng: Engine, board: Board, side: int) -> Move | None:
    """Pick randomly among the top few root moves (diversifies openings)."""
    moves = board.legal_moves(side)
    if not moves:
        return None
    # Cheap shallow scores for variety; full search would be wasteful here.
    shallow = Engine(max_depth=2, time_limit=5.0)
    shallow._ext_budget = shallow.EXT_BUDGET
    shallow._killers = {}
    shallow._history = {}
    shallow._deadline = None
    scored = []
    for mv in moves:
        board.make(mv)
        s = -shallow._negamax(board, -side, 1, -10**9, 10**9)
        board.unmake()
        scored.append((s, mv))
    scored.sort(key=lambda x: x[0], reverse=True)
    top = scored[: min(4, len(scored))]
    return random.choice(top)[1]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--games", type=int, default=100)
    ap.add_argument("--depth", type=int, default=4)
    ap.add_argument("--out", default="data/selfplay.jsonl")
    args = ap.parse_args()

    t0 = time.time()
    n_pos = 0
    with open(args.out, "w") as f:
        for gi in range(args.games):
            history, winner = play_one_game(args.depth)
            val = {"han": 1.0, "cho": -1.0}.get(winner, 0.0)
            for flat, mv, side in history:
                rec = {"b": [int(x) for x in flat], "m": list(mv), "v": val, "s": side}
                f.write(json.dumps(rec) + "\n")
                n_pos += 1
            if (gi + 1) % 10 == 0:
                dt = time.time() - t0
                print(f"  {gi+1}/{args.games} games, {n_pos} positions, {dt:.0f}s")
    print(f"done: {n_pos} positions -> {args.out} ({time.time()-t0:.0f}s)")


if __name__ == "__main__":
    main()
